### ISSUE TITLE
Example in documentation does not work, because done is not called in before (and after)

### ISSUE THREAD

**Issue by scharf** [rjz/supertest-session#6]
The documented example does not work as expected, because the `before`does not call `done`.

It should look like:

```javascript
before(function (done) {
  this.sess = new Session();
  done();
});

after(function (done) {
  this.sess.destroy();
  done();
});
```

**Comment by scharf** [comment]
see https://github.com/rjz/supertest-session/issues/6

**Comment by rjz** [comment]
Both `Session` and `Session::destroy` should be synchronous methods. In mocha, we should be able to get away with omitting done—but I'm probably missing something, here!

Would you mind detailing the testing setup (runner, version) and any other details that require the use of `done`?

**Comment by scharf** [comment]
you are right! There is no need for calling done()!
