### ISSUE TITLE
Missing documentation for manipulating session BEFORE calling methods

### ISSUE THREAD

**Issue by brugnara** [rjz/supertest-session#8]
This is the how to do, hoping that will be putted into documentation:

```js
    var session = new Session();
    // here we are setting the session value
    session.app.request.session = {
      user: {
        account: {
          username: USERNAME
        }
      }
    };
    session
      .post(util.format(urlAnsw, _id, 'FAKEUSER'))
      .expect(400)
      .expect('Content-Type', /json/)
      .end(function(err, res) {
        res.body.should.have.property('ok', false);
        res.body.err.should.be.exactly('Username is not the one online from this IP.');
        session.destroy();
        done();
      })
```

**Comment by rjz** [comment]
Thanks, @brugnara! Would you be willing to open a pull request containing with a test for the expected behavior?

**Comment by brugnara** [comment]
This works with express but not with connect. I'm trying to add the test case but I'm unable to get `session.app.request` object. Any hints? If not, adding a new `express_spec.js` could be something you will like?

Thanks in advice.

**Comment by brugnara** [comment]
Just forget this.
The session can be setted the way I wrote, without this module. Sorry about that.

**Comment by rjz** [comment]
Ah, no worries! Thanks for taking a look (and happy testing!)
